package tracer

import (
	"crypto/md5"
	"encoding/hex"
	"fmt"
	"testing"
)

// TestParseClientHello_RealCurlCapture_PeetWS is the FULLY-EXTERNAL ground-truth
// check: a REAL curl 8.5.0 / OpenSSL 3.0.13 ClientHello captured off the wire
// (curl --trace) against tls.peet.ws on 2026-06-17, with reference fingerprints
// computed INDEPENDENTLY by peet.ws. Nothing here is generated by our code.
//
// JA3 matches peet.ws exactly. JA4 deliberately does NOT, and that is a FINDING:
// peet.ws (TrackMe) is non-compliant with the FoxIO JA4 spec — it drops the
// padding extension (0x0015) from the JA4_c hash, whereas the spec
// (technical_details/JA4.md: the padding extension "is NOT excluded") keeps it.
// peet reports JA4_c 375ca2c5e164; the FoxIO-correct value our spec-following
// ComputeJA4 produces is b26ce05bbdd6. The two differ ONLY by ext 0x0015 (proven
// by sha256'ing both lists). We assert the FoxIO-correct value. OPSEC/attribution
// caveat: peet.ws JA4 is NOT directly comparable to FoxIO/Wireshark JA4 when a
// padding extension is present.
func TestParseClientHello_RealCurlCapture_PeetWS(t *testing.T) {
	const helloHex = "1603010200010001fc03039d8581346108dd2736567df2a8aa26875e6bb19f973d0a23221382651de60b7920d8568b73753b5af637fff2c4d54890ae0a198d903107ed98e4f631672dbc278a003e130213031301c02cc030009fcca9cca8ccaac02bc02f009ec024c028006bc023c0270067c00ac0140039c009c0130033009d009c003d003c0035002f00ff0100017500000010000e00000b746c732e706565742e7773000b000403000102000a00160014001d0017001e00190018010001010102010301040010000e000c02683208687474702f312e31001600000017000000310000000d002a0028040305030603080708080809080a080b080408050806040105010601030303010302040205020602002b00050403040303002d00020101003300260024001d0020b4a0de5aba8a79c7f99522b9bac4db330018663621f6cd1a04ed5d3a32b65902001500b60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
	const wantJA3Hash = "0149f47eabf9a20d0893e2a44e5a6323"
	const wantJA4 = "t13d3112h2_e8f1e7e78f70_b26ce05bbdd6" // FoxIO-spec-correct; peet.ws reports ..._375ca2c5e164 (drops ext 0x0015)

	raw, err := hex.DecodeString(helloHex)
	if err != nil {
		t.Fatal(err)
	}
	ch, err := ParseClientHello(raw)
	if err != nil {
		t.Fatalf("ParseClientHello on real curl capture: %v", err)
	}
	if got := fmt.Sprintf("%x", md5.Sum([]byte(ch.JA3()))); got != wantJA3Hash {
		t.Errorf("JA3 hash vs peet.ws:\n  got  %s\n  want %s\n  ja3  %s", got, wantJA3Hash, ch.JA3())
	}
	if got := ch.JA4(); got != wantJA4 {
		t.Errorf("JA4 vs FoxIO spec:\n  got  %s\n  want %s", got, wantJA4)
	}
}
